"use client"

/* eslint-disable react/no-unescaped-entities */

import { useState } from "react"
import { ArrowRight, Bell, ChevronDown, ChevronRight, Headphones, Heart, Menu, MessageCircle, Search, ShieldCheck, Sparkles, Star, UserRound, X } from "lucide-react"

const experts = [
  { name: "Dr. Meera Sharma", specialty: "Vedic Astrology · Kundli", language: "Hindi, English", rate: "₹25/min", rating: "4.9", reviews: "2,841", image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=300&q=85", online: true, tag: "Top astrologer" },
  { name: "Acharya Raghav", specialty: "Vastu · Numerology", language: "Hindi, English", rate: "₹18/min", rating: "4.8", reviews: "1,922", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=85", online: true, tag: "Recommended" },
  { name: "Kavya Tarot", specialty: "Tarot Reading · Love", language: "Hindi, English", rate: "₹22/min", rating: "4.9", reviews: "3,106", image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=85", online: false, tag: "Popular" },
  { name: "Pt. Anant Shukla", specialty: "Vedic Astrology · Puja", language: "Hindi, Sanskrit", rate: "₹30/min", rating: "4.9", reviews: "876", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=85", online: true, tag: "Verified" },
]

const categories = [
  ["Vedic Astrology", "✦", "Understand your life path"], ["Tarot Reading", "♧", "Find clarity in the cards"], ["Kundli Making", "ॐ", "Your complete birth chart"], ["Numerology", "९", "The power in your numbers"], ["Vastu Shastra", "⌂", "Balance your space"], ["Puja & Remedies", "🪔", "Simple sacred solutions"],
]

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [tab, setTab] = useState("All")
  const [selectedAmount, setSelectedAmount] = useState("500")

  return <div className="astro-site">
    <div className="astro-notice"><Bell size={13} /> <span>Get 20% extra on your first consultation</span><a href="#experts">Talk to an astrologer <ArrowRight size={12} /></a></div>
    <header className="astro-header"><a className="astro-logo" href="#home"><span className="astro-logo-mark">ॐ</span><span><strong>book<span>arti</span></strong><small>Guidance with श्रद्धा</small></span></a><nav className={menuOpen ? "show" : ""}><a href="#experts">Astrologers</a><a href="#services">Services <ChevronDown size={13} /></a><a href="#puja">Puja & Remedies</a><a href="#learn">Learn astrology</a><a className="login-link" href="#login"><UserRound size={15} /> Login</a><a className="wallet-link" href="#wallet">₹ 0 <span>Add money</span></a></nav><button className="astro-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X /> : <Menu />}</button></header>

    <main id="home">
      <section className="astro-hero"><div className="astro-hero-inner"><div className="astro-hero-copy"><span className="astro-eyebrow"><Sparkles size={14} /> India's trusted spiritual guidance</span><h1>Answers to life&apos;s<br /><em>big questions.</em></h1><p>Talk to a verified astrologer, tarot reader or vastu expert over chat or call. Personal guidance rooted in ancient wisdom, made easy for today.</p><div className="hero-search"><Search size={17} /><input placeholder="What would you like to know?" /><button>Ask now <ArrowRight size={15} /></button></div><div className="hero-tags"><span>Try asking:</span><a href="#experts">Love & relationships</a><a href="#experts">Career & money</a><a href="#experts">Marriage</a></div><div className="hero-trust"><div className="tiny-avatars"><i /><i /><i /><i /></div><span><strong>2 lakh+ people</strong> got their answers this month</span></div></div><div className="astro-hero-art"><div className="planet planet-large" /><div className="planet planet-small" /><div className="star-field">✦　⋆　✧<br />　✧　✦　⋆<br />⋆　　✧</div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="birth-chart"><div className="chart-header">YOUR BIRTH CHART <span>✦</span></div><div className="chart-diamond"><b>☉</b><i>☽</i><em>♃</em><small>♄</small></div><strong>Every chart<br /><em>has a story.</em></strong></div><div className="hero-quote">“The stars incline,<br />they do not decide.”</div></div></div></section>

      <section className="quick-services" id="services"><div className="quick-label">Explore guidance</div><div className="category-grid">{categories.map(([name, icon, sub]) => <a href="#experts" className="category-item" key={name}><span className="category-icon">{icon}</span><span><strong>{name}</strong><small>{sub}</small></span><ChevronRight size={15} /></a>)}</div></section>

      <section className="astro-section" id="experts"><div className="section-head"><div><span className="section-eyebrow">Real people. Real guidance.</span><h2>Talk to someone<br /><em>who understands.</em></h2><p>Every expert is verified for experience, knowledge and empathy.</p></div><a href="#experts" className="outline-link">View all astrologers <ArrowRight size={15} /></a></div><div className="expert-tabs">{["All", "Astrologers", "Tarot readers", "Numerologists", "Vastu experts"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div><div className="experts-grid">{experts.map((expert) => <article className="expert-card" key={expert.name}><div className="expert-image" style={{ backgroundImage: `url(${expert.image})` }}><span className="expert-tag">{expert.tag}</span><button aria-label="Add to favourites"><Heart size={15} /></button><span className={expert.online ? "online-status" : "offline-status"}>{expert.online ? "Online" : "Busy"}</span></div><div className="expert-body"><h3>{expert.name} <ShieldCheck size={14} /></h3><p>{expert.specialty}</p><small>{expert.language}</small><div className="expert-meta"><span><Star size={13} fill="currentColor" /> {expert.rating} <i>({expert.reviews})</i></span><strong>{expert.rate}</strong></div><div className="expert-actions"><a href="#booking"><MessageCircle size={14} /> Chat</a><a href="#booking"><Headphones size={14} /> Call</a></div></div></article>)}</div></section>

      <section className="consultation-banner"><div className="consult-copy"><span className="section-eyebrow">Not sure where to begin?</span><h2>Let us find the<br /><em>right guide for you.</em></h2><p>Tell us what&apos;s on your mind. Our matching assistant will recommend an expert in under a minute.</p><a href="#booking" className="saffron-button">Find my astrologer <ArrowRight size={15} /></a></div><div className="chat-preview"><div className="chat-top"><span className="live-dot" /> BookArti Guide <small>Always here to help</small></div><div className="chat-message bot">Namaste 🙏<br />What would you like guidance on today?</div><div className="chat-choices"><span>Love & marriage</span><span>Career</span><span>My kundli</span></div><div className="chat-message user">I&apos;m at a crossroads in my career.</div><div className="chat-message bot typing">Finding a guide for you <i /> <i /> <i /></div></div></section>

      <section className="daily-section" id="learn"><div className="daily-art"><div className="daily-sun">☀</div><div className="daily-symbol">ॐ</div><span className="daily-star one">✦</span><span className="daily-star two">✧</span><span className="daily-star three">⋆</span></div><div className="daily-copy"><span className="section-eyebrow">Your daily guidance</span><h2>Start the day<br /><em>with intention.</em></h2><p>Get your personalised daily horoscope, moon guidance and simple remedies for a more mindful day.</p><a className="text-button" href="#booking">Read today&apos;s horoscope <ArrowRight size={15} /></a><div className="zodiac-row"><span>♈</span><span>♉</span><span>♊</span><span>♋</span><span>♌</span><span>♍</span><span>♎</span><span>♏</span><span>♐</span><span>♑</span><span>♒</span><span>♓</span></div></div></section>

      <section className="puja-remedy" id="puja"><div className="section-head"><div><span className="section-eyebrow">Guidance meets devotion</span><h2>Sacred remedies,<br /><em>made simple.</em></h2></div><p>When a reading points to a remedy, we help you take the next step with an authentic puja performed by a verified pandit.</p></div><div className="remedy-grid"><Remedy icon="ॐ" title="Rudrabhishek Puja" text="For peace, health and strength" price="₹1,100" /><Remedy icon="श्री" title="Navgraha Shanti" text="For dosha nivaran and balance" price="₹2,100" /><Remedy icon="🪔" title="Maha Mrityunjaya Jaap" text="For healing and protection" price="₹1,501" /></div></section>

      <section className="kundli-section"><div className="kundli-copy"><span className="section-eyebrow">Your cosmic blueprint</span><h2>Know yourself<br /><em>a little deeper.</em></h2><p>Get your detailed Janam Kundli with planetary positions, dasha analysis and personalised insights from a trusted Vedic astrologer.</p><a href="#booking" className="saffron-button">Create my kundli <ArrowRight size={15} /></a><small><ShieldCheck size={13} /> Secure & private · Instant delivery</small></div><div className="kundli-art"><div className="kundli-circle"><span>☉</span><span>☽</span><span>♃</span><span>♄</span><b>ॐ</b></div><div className="kundli-card"><small>JANAM KUNDLI</small><strong>Priya Sharma</strong><span>12 October 1994 · New Delhi</span><i>✦ Your journey, decoded</i></div></div></section>

      <section className="seva-strip" id="wallet"><div><span className="section-eyebrow">And when your heart calls for seva</span><h2>Offer a little.<br /><em>Change a lot.</em></h2><p>Feed an animal, support a family, restore a temple or sponsor a pilgrim&apos;s yatra.</p></div><div className="seva-action"><div className="seva-amounts">{["101", "501", "1,001"].map((item) => <button className={selectedAmount === item ? "selected" : ""} onClick={() => setSelectedAmount(item)} key={item}>₹{item}</button>)}</div><a href="#wallet" className="light-button">Offer seva <Heart size={15} fill="currentColor" /></a><small><ShieldCheck size={13} /> Every contribution is verified</small></div></section>

      <section className="app-promo"><div><span className="section-eyebrow">Guidance, wherever you are</span><h2>Your answers.<br /><em>One app.</em></h2><p>Chat with an expert, check your horoscope, book a puja and keep your spiritual journey close.</p><div className="store-row"><a href="#login"><b></b><small>Download on the<strong>App Store</strong></small></a><a href="#login"><b>▶</b><small>GET IT ON<strong>Google Play</strong></small></a></div></div><div className="app-device"><div className="device-inner"><span className="device-time">9:41 <i>● ● ●</i></span><span className="device-om">ॐ</span><h4>Namaste, Priya</h4><small>What would you like to explore?</small><div className="device-box"><span>DAILY HOROSCOPE</span><strong>Your day has a<br /><em>new possibility.</em></strong><b>Read now →</b></div><div className="device-bottom">⌂　◉　ॐ　♡</div></div></div></section>
    </main>
    <footer className="astro-footer"><div className="footer-brand"><a className="astro-logo" href="#home"><span className="astro-logo-mark">ॐ</span><span><strong>book<span>arti</span></strong><small>Guidance with श्रद्धा</small></span></a><p>Ancient wisdom. Modern guidance.<br />For every question life brings.</p></div><div className="footer-links"><div><b>Astrology</b><a href="#experts">Talk to astrologers</a><a href="#services">Tarot reading</a><a href="#services">Kundli</a></div><div><b>Devotion</b><a href="#puja">Book a puja</a><a href="#live">Live darshan</a><a href="#wallet">Seva & donations</a></div><div><b>Support</b><a href="#booking">Help centre</a><a href="#booking">Contact us</a><a href="#booking">Privacy & terms</a></div></div><div className="footer-end"><span>© 2025 BookArti Technologies Pvt. Ltd.</span><span>ॐ शान्तिः</span></div></footer>
  </div>
}

function Remedy({ icon, title, text, price }: { icon: string; title: string; text: string; price: string }) { return <a className="remedy-card" href="#booking"><span className="remedy-icon">{icon}</span><span><h3>{title}</h3><small>{text}</small><strong>{price} <i>onwards</i></strong></span><ChevronRight size={16} /></a> }
